spring:
  application:
    name: Clean Driver
  datasource:
    url: jdbc:mysql://localhost:3306/clean_drive?ServerTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  show-sql: true
